In [1]:
# 딥런치 스터디 2주차

In [20]:
## 과제 1. 구구단 프로그램 만들기

def calculate_multiplication_table(input_value, number_of_times):
     # 몇 번 곱할 것인지를 지정한 리스트. 예시로 number_of_times 를 9로 입력하면 [1, 2, 3, 4, ..., 8, 9] 를 가지게 됩니다.
    number_of_times_list = range(1, number_of_times + 1)
    # 리스트 컨프리헨션 https://wikidocs.net/22 을 이용해 입력값을 number_of_times_list 리스트의 각 요소와 곱해 구구단을 만듭니다.
    return [i * input_value for i in number_of_times_list]

In [21]:
calculate_multiplication_table(2, 9)

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [39]:
## 과제 2. 계산기 프로그램 만들기

def calculator():
    # calculator() 함수에서만 작동하는 사칙연산 내부 함수입니다.
    def add(a, b):
        return a + b
    def sub(a, b):
        return a - b
    def mul(a, b):
        return a * b
    def div_int(a, b):
        return int(a / b)
    def div_float(a, b):
        return float(a / b)
    def remainder(a, b):
        return a % b
    def is_input_b_zero(b):
        if b == 0:
            print('나눗셈을 위한 두번째 값은 0보다 큰 값을 입력해주세요.')
            return False
        else:
            return True


    input_a = int(input('계산할 첫번째 값을 입력하세요. : '))
    input_b = int(input('계산할 두번째 값을 입력하세요. : '))
    action_type = input('''
        원하는 연산을 선택하세요.
        1. 더하기
        2. 빼기
        3. 곱하기
        4. 정수 나누기
        5. 실수 나누기
        6. 나머지 구하기
        7. 계산기 종료
    ''')
    print('두 개의 값 : {0} 그리고 {1}'.format(input_a, input_b))

    # match-case 문을 이용해 action 이 무엇인지에 따른 계산을 수행합니다. https://wikidocs.net/173398
    if action_type =='1':
        print('결과: ', add(input_a, input_b))
    elif action_type == '2':
        print('결과: ', sub(input_a, input_b))
    elif action_type == '3':
        print('결과: ', mul(input_a, input_b))
    elif action_type == '4':
        if is_input_b_zero(input_b) == True:
            print('결과: ', div_int(input_a, input_b))
    elif action_type == '5':
        if is_input_b_zero(input_b) == True:
            print('결과: ', div_float(input_a, input_b))
    elif action_type == '6':
        if is_input_b_zero(input_b) == True:
            print('결과: ', remainder(input_a, input_b))
    else:
        print('프로그램을 종료합니다.')

In [40]:
calculator()

계산할 첫번째 값을 입력하세요. : 3
계산할 두번째 값을 입력하세요. : 3

        원하는 연산을 선택하세요.
        1. 더하기
        2. 빼기
        3. 곱하기
        4. 정수 나누기
        5. 실수 나누기
        6. 나머지 구하기
        7. 계산기 종료
    3
두 개의 값 : 3 그리고 3
결과:  9

In [53]:
## 과제 3. 
### 3.1. n 개의 정수를 가진 리스트를 정렬하기
def sort_list_values(target_list):
    has_zero = False
    minus_list = []
    plus_list = []
    for val in target_list:
        if val > 0:
            plus_list.append(val)
        elif val < 0:
            minus_list.append(val)
        else:
            # target_list 에 0인 요소가 있는 경우.
            has_zero = True
    # 음수 리스트, 양수 리스트로 구분했으니 이제 결과를 구합니다.
    if has_zero:
        return minus_list + [0] + plus_list
    else:
        return minus_list + plus_list

In [54]:
sort_list_values([-1, 1, 3, -2, 2, 0])

[-1, -2, 0, 1, 3, 2]

In [70]:
### 3.2.
def solve_from_name_string(name_string):
    name_list = name_string.split(',')
    # 3.2.1. 김씨와 이씨는 각각 몇 명?
    print('1번. ', '김씨: ', len([name for name in name_list if name[0] == '김']), ', 이씨: ', len([name for name in name_list if name[0] == '이']))
    # 3.2.2. "이재영" 이름은 몇 번 반복?
    print('2번. ', name_list.count('이재영'))
    # 3.2.3. 중복을 제거한 이름을 출력하기
    def get_list_without_duplicate():
        result = []
        for name in name_list:
            # result 라는 리스트 안에 같은 이름이 없을 때에만 추가하도록 조건을 설정합니다.
            if name not in result:
                result.append(name)
        return result
    list_without_duplicate = get_list_without_duplicate()
    print('3번. ', list_without_duplicate)
    # 3.2.4. 중복을 제거한 이름을 오름차순으로 출력하기
    list_without_duplicate.sort()
    print('4번. ', list_without_duplicate)

# namefa('이유덕,이재영,권종표,이재영,박민호,강상회,이재영,김지완,최승혁,이성연,박영서,박민호,전경헌,송정환,김재성,이유덕,전경헌')

In [71]:
solve_from_name_string('이유덕,이재영,권종표,이재영,박민호,강상회,이재영,김지완,최승혁,이성연,박영서,박민호,전경헌,송정환,김재성,이유덕,전경헌')

1번.  김씨:  2 , 이씨:  6
2번.  3
3번.  ['이유덕', '이재영', '권종표', '박민호', '강상회', '김지완', '최승혁', '이성연', '박영서', '전경헌', '송정환', '김재성']
4번.  ['강상회', '권종표', '김재성', '김지완', '박민호', '박영서', '송정환', '이성연', '이유덕', '이재영', '전경헌', '최승혁']